name: Publish Eslint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**'
      - '!eslint/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install --shamefully-hoist --prefix eslint

      - name: Publish
        uses: znck/pnpm@v0.1.0-alpha.1
        with:
          args: publish --access public
          secrets: ${{ secrets.NPM_TOKEN }}
