name: Publish Stylelint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**'
      - '!stylelint/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install --shamefully-hoist --prefix stylelint
      # - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: stylelint/package.json