name: Publish Textlint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**'
      - '!textlint/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install --prefix textlint
      # - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: textlint/package.json